Use printf instead of echo
For readability, change echo to printf function to print info and
error messages.

diff --git a/bin/pyenv-pip-upgrade b/bin/pyenv-pip-upgrade
--- a/bin/pyenv-pip-upgrade
+++ b/bin/pyenv-pip-upgrade
@@ -19,12 +19,11 @@ IFS=$'\n\t'
 
 # functions
 function __msg_error () {
-  echo -e "\e[1;31m[ERROR]: ${1}\e[0m" >&2
+  printf '\e[1;31m[ERROR]: %s\n\e[0m' "${1}" >&2
 }
 
-
 function __msg_info () {
-  echo -e "\e[1;33m[INFO]: ${1}\e[0m"
+  printf '\e[1;33m[INFO]: %s\n\e[0m' "${1}"
 }
 
 
